import { Share2, Download, Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { useState } from "react";

interface ShareTripProps {
  tripId: string;
  boardingCity: string;
  destinationCity: string;
  duration: number;
  budget: number;
  startDate?: string | null;
}

export function ShareTrip({ tripId, boardingCity, destinationCity, duration, budget, startDate }: ShareTripProps) {
  const [copied, setCopied] = useState(false);

  const shareText = `🌍 Check out my trip plan!\n\n📍 ${boardingCity} → ${destinationCity}\n📅 ${duration} days\n💰 Budget: ₹${budget.toLocaleString()}\n${startDate ? `🗓️ Starting: ${startDate}\n` : ""}\nPlanned with Travello — AI Trip Planner`;

  const shareLink = async () => {
    if (navigator.share) {
      try {
        await navigator.share({ title: `Trip to ${destinationCity}`, text: shareText });
      } catch {
        // User cancelled
      }
    } else {
      await navigator.clipboard.writeText(shareText);
      setCopied(true);
      toast.success("Trip details copied to clipboard!");
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const downloadSummary = () => {
    const content = `
TRAVELLO - TRIP SUMMARY
========================

Route: ${boardingCity} → ${destinationCity}
Duration: ${duration} days
Budget: ₹${budget.toLocaleString()}
${startDate ? `Start Date: ${startDate}` : "Start Date: Not set"}

========================
Generated by Travello — AI Trip Planner
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Travello-${destinationCity}-Trip.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Trip summary downloaded!");
  };

  return (
    <div className="bg-card rounded-2xl p-6 border border-border">
      <div className="flex items-center gap-3 mb-4">
        <div className="w-10 h-10 rounded-lg gradient-primary flex items-center justify-center">
          <Share2 className="w-5 h-5 text-primary-foreground" />
        </div>
        <div>
          <h3 className="font-display font-semibold">Share Trip</h3>
          <p className="text-sm text-muted-foreground">Share with friends & family</p>
        </div>
      </div>
      <div className="flex flex-wrap gap-3">
        <Button onClick={shareLink} variant="outline" className="gap-2">
          {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
          {copied ? "Copied!" : "Share Details"}
        </Button>
        <Button onClick={downloadSummary} variant="outline" className="gap-2">
          <Download className="w-4 h-4" /> Download Summary
        </Button>
      </div>
    </div>
  );
}
